### ISSUE TITLE
Icons Not displayed in Safari

### ISSUE THREAD

**Issue by tomconklin** [catalyst/moodle-mod_facetoface#1]
F2F icon will not display when browsing 'Manage Activities' and 'Plugins Overview' on Safari Browser. This is ONLY on Safari (Latest), if I delete two icons from mod/facetoface/pix and leave only the .png or .gif the icon will render.

**Comment by danmarsden** [comment]
I haven't been able to reproduce this - please let us know if this is still an issue with the latest code available here in github. thanks.
