### ISSUE TITLE
Supported versions in README.md

### ISSUE THREAD

**Issue by luisdev** [catalyst/moodle-mod_facetoface#119]
The [README.md](https://github.com/catalyst/moodle-mod_facetoface#readme) file for this plugin only mentions the  MOODLE_34_STABLE and MOODLE_311_STABLE branches. Is this plugin supported in Moodle 4.x? If so, please update the README.md file with the latest info.

**Comment by danmarsden** [comment]
thanks for the report - I've added that branch to the readme file now! :-)
