### ISSUE TITLE
MIssing Item id when you make changes 

### ISSUE THREAD

**Issue by gemguardian** [catalyst/moodle-mod_facetoface#125]
versie 4.0.11 / 2023020107

When I update the FacetoFace activity, by example by changes the calenderoptions, I see a notification "Missing itemid, maybe caused by unset Maxfiles option. 

Is this a bug or am I missing a setting? 

![image](https://user-images.githubusercontent.com/16559999/233039411-f84ed386-c32c-4405-a93d-03c438236dce.png)

**Comment by skodak** [comment]
this should have been fixed by #129
