### ISSUE TITLE
substr()-fuction not utf-8 compatible

### ISSUE THREAD

**Issue by rosa-aurora** [catalyst/moodle-mod_facetoface#126]
If shortname in Calendar options is empty, F2F will create one using substr(), which isn't compatible with utf-8 and will result in a database error if there are letters like Ä and Ö at the end of the shortname. Error in the screenshot below appeared when trying to save changes to F2F settings (the name of the F2F was "F2F name with ÄÖÅ").

<img width="1092" alt="Screenshot 2023-09-14 at 10 14 18" src="https://github.com/catalyst/moodle-mod_facetoface/assets/143802673/2ba00053-66b4-4c5c-9c72-33ea47b77f28">

**Comment by danmarsden** [comment]
Thanks for the report! - if you have internal development capabilities, pull requests are always welcome, otherwise feel free to reach out privately if you would like to fund improvements to this plugin.

thanks!
