### ISSUE TITLE
Strings missing from lang.moodle.org

### ISSUE THREAD

**Issue by jarvil1** [catalyst/moodle-mod_facetoface#127]
Hello,
I cannot find strings 

- signuptype
- signuptype_help 
- single
- multiple
- multiplesignupmethod
- multiplesignuppersession 
- multiplesignupperactivity
- signupforstream
- addtoallsessions
- multiplesignupmethod_help

from https://lang.moodle.org

![image](https://github.com/catalyst/moodle-mod_facetoface/assets/53904029/3f82abab-89ab-47e0-8e23-18cf47fb3f95)
![image](https://github.com/catalyst/moodle-mod_facetoface/assets/53904029/ec89da34-1660-482a-9c56-6df7d9b1d7cd)

**Comment by danmarsden** [comment]
Thanks for the report - this will be because we haven't pushed the latest version from github into the moodle.org plugins db recently - I've just done that now and it should appear in amos later today - thanks!
