### ISSUE TITLE
Capability for creating a site event

### ISSUE THREAD

**Issue by MURBASLMS** [catalyst/moodle-mod_facetoface#134]
Hi, would it be possible to add a capability to control the ability to create a f2f activity as a site event? 

we have the odd occasion where activities have been set up as site events by mistake and the result it it displaying in all courses in upcoming events. 

cheers

**Comment by danmarsden** [comment]
Hi there  anything is possible :-) if you have internal development capabilities then pull requests are always welcome, alternatively feel free to reach out privately if you would like to fund the time for a developer to improve the plugin to meet your needs.
