### ISSUE TITLE
Moodle 4.3 compatible version

### ISSUE THREAD

**Issue by michael-milette** [catalyst/moodle-mod_facetoface#136]
Hi @danmarsden , 

Do you have any thoughts on when a Moodle 4.3 compatible version might become available?

Best regards,

Michael Milette

**Comment by danmarsden** [comment]
We don't have many clients using this plugin and I don't know of any currently planning an upgrade to 4.3 in the short term, but please test it yourself and let us know if you have any issues by reporting them to the tracker here.
