### ISSUE TITLE
New availability plugin to support Face-to-face use cases 

### ISSUE THREAD

**Issue by jeremy-schweitzer** [catalyst/moodle-mod_facetoface#144]
Hi all - wasn't sure of a better way to notify you, but Open LMS engaged Petr Skoda to create a plugin for us that we just submitted to the plugins database. 

The plugin enables access restrictions based on booking for a specific facetoface session. You can have access open as soon as the booking occurs or later on the starting date of the related session. 

https://moodle.org/plugins/availability_facetoface
https://tracker.moodle.org/browse/CONTRIB-9510

Would love any feedback or thoughts related to this - hopefully the community finds it beneficial.

**Comment by danmarsden** [comment]
Thanks @jeremy-schweitzer! - yes I saw that come through the plugin review queue and was happy to see David was able to pick it up to do the review.

Feel free to drop a PR in to add something to the readme mentioning your plugin under a title like "supporting availability plugin" that covers a one liner on what it does and a link to the plugins db to help direct others to your plugin too! - always great to see stuff from @skodak too! :-)
