### ISSUE TITLE
Duplicate descriptions posting

### ISSUE THREAD

**Issue by Mattncan** [catalyst/moodle-mod_facetoface#160]
When adding descriptions to an activity it duplicates the description on the sessions page. 

![duplicate description](https://github.com/catalyst/moodle-mod_facetoface/assets/170472828/32236dfe-c8a3-4a7d-8d23-afdd35c835f0)

**Comment by danmarsden** [comment]
What Moodle version are you using?

**Comment by Mattncan** [comment]
4.3+ (Build: 20231201)

**Comment by danmarsden** [comment]
thanks - I suspected that was the case - I've just pushed a fix through for that now - Moodle now prints the description as part of the core page header api inside activity plugins so we don't need to explicitly include it.
