### ISSUE TITLE
Invalid get_string() identifier: 'multidate' or component 'facetoface'

### ISSUE THREAD

**Issue by fsjoyti** [catalyst/moodle-mod_facetoface#17]
Here is a screen shot of the message I got 

![screenshot from 2017-06-06 15-12-37](https://user-images.githubusercontent.com/10965471/26849661-b35dcecc-4aca-11e7-9a7c-70b6f0472576.png)

**Comment by danmarsden** [comment]
thanks for the report - I've pushed a patch through for that.
