### ISSUE TITLE
Enrollment without role

### ISSUE THREAD

**Issue by jeremy-schweitzer** [catalyst/moodle-mod_facetoface#25]
If a teacher or trainer adds a user to a F2F session without first enrolling the user F2F adds the user to the course using the manual enrollment method. However, it doesn't apply a user role. 

Without a role the user isn't able to see most course content - including the F2F instance. Manual enrollments include a default user role setting. It would seem reasonable to apply that role automatically.

**Comment by danmarsden** [comment]
Thanks Jeremy - feel free to help us work on this.

**Comment by pnbowen** [comment]
Hi Dan,

I just noted this as one I had worked on years ago. There was a moodletracker raised on it, but when you guys took over the module, you closed it.

https://tracker.moodle.org/browse/CONTRIB-5095

I have been using the workaround for many years now, and it works well. We do hard code to '5', but that is the role we want students to have in a course anyway.

Cheers
Peter

**Comment by danmarsden** [comment]
thanks - hopefully someone might develop a proper fix at some point.

**Comment by jtsafran** [comment]
https://github.com/catalyst/moodle-mod_facetoface/blob/master/editattendees.php#L91

We need to update that line to send a role https://github.com/moodle/moodle/blob/master/lib/enrollib.php#L1040

Now to figure out how best to decide on that role.  Maybe in a dropdown within the mod edit screen?  I think that makes the most sense.

**Comment by danmarsden** [comment]
Sure - feel free to submit a pull request - although I'm not convinced this should be using the "manual" enrolment - I wonder if this should be changed to check if self-enrolment is enabled in this course which will already have a role assigned to use.

In any case - happy to receive a pull request that deals with it somehow.

**Comment by snack753** [comment]
Hi all,
encountered this issue yesterday too. Didn't realize where this behavior was coming from, however reading this issue I can confirm this is still an issue.
