### ISSUE TITLE
Export to Excel producing spreadsheet that goes to column AUG

### ISSUE THREAD

**Issue by alanrobinson5538** [catalyst/moodle-mod_facetoface#29]
Updated to 

Face-to-Face
mod_facetoface
3.4.1
2018062000

using Moodle Moodle 3.4.2+ (Build: 20180512).

Export to Excel the sessions is producing spreadsheet that has hundreds of columns and is not usable to see who is booked on to which session.  Was fine in previous verson.

**Comment by danmarsden** [comment]
Thanks for the report, feel free to help us work on this.

Have you tried exporting the ods format and opening that in Excel to see if it has the same issues?

**Comment by alanrobinson5538** [comment]
Hi Dan, today I spent a little time on this....  Essentially I backed up the lib.php file in the facetoface directory, downloaded the previous version - 3.2.1 and copied the text in the lib.php file from the new download, relating to the export:

From here:

facetoface_download_attendance()

Down to the end of the whole section relating to  download attendance.  

Then I replaced the whole section from facetoface_download_attendance() down to the end in the lib.php file on the Moodle server.

Everything works great again for the export to excel.

**Comment by danmarsden** [comment]
Cool thanks - I've just had another look at this - I didn't realise you meant it had happened so recently - looks like a bug with this patch on this line:
https://github.com/catalyst/moodle-mod_facetoface/commit/b20af2e0222223b35132790ab8d17865d359e3f4#diff-828043dc9f8d10ccd58ff8b96297794fR1491

should be $j = facetoface_write_activity_attendance_helper ... I'll fix that now.

**Comment by alanrobinson5538** [comment]
Brilliant, update received.

Last question from me, is there any way that we can get the “group” or “cohort”that the learner is in on the face to face course on the export?  It would make my life so much easier.  I don’t know where to start.

All of my learners (3900 of them in the facetoface courses) are set up in System cohorts, which are then replicated in the individual course in groups.

Alan

**Comment by danmarsden** [comment]
anything is possible with some development - unfortunately we don't have any time for feature development/improvements that aren't funded but we're always happy to receive pull requests! - feel free to get in touch privately if you would like to fund any improvements to the facetoface plugin. Thanks!
