### ISSUE TITLE
Session dates not writing to Excel/ODS Attendance export

### ISSUE THREAD

**Issue by jtsafran** [catalyst/moodle-mod_facetoface#31]
Using the current repo version of 2018070500 with Moodle 3.4.  

It looks like the new facetoface_write_activity_attendance_helper function needs to have $sessiondate added as a parameter as line 1599 will always be empty: https://github.com/catalyst/moodle-mod_facetoface/blob/master/lib.php#L1599

Thanks!
Jesse

**Comment by danmarsden** [comment]
Thanks Jesse, 

I've tidied that function up a bit more and that should have fixed it!
