### ISSUE TITLE
Version of lib.php different on GitHub and Moodle.org

### ISSUE THREAD

**Issue by michael-milette** [catalyst/moodle-mod_facetoface#34]
I am planning on adding a feature to optionally disable the sending out of emails to students. I noticed that the version of lib.php here on GitHub (master branch) is different than the version I downloaded from Moodle.org.

The version.php files between the two versions are identical so I am not sure which is newer.

Could you please tell me which of the two has the more recent version of lib.php? I suspect that it is the one on GitHub but just want to be sure before I begin working on it.

**Comment by danmarsden** [comment]
Hi Michael!
If you take a look at the commit history here it will show you why. There are 3 commits since the last version bump. We usually only bump versions when a new version is published in the plugins db.

(All the latest code is here in github) - thanks!
