### ISSUE TITLE
Valid email address not allowed in facetoface_fromaddress

### ISSUE THREAD

**Issue by hamishdewe** [catalyst/moodle-mod_facetoface#38]
The plugin will not allow the use of our valid domain '@rhapsody.health'.

**Comment by danmarsden** [comment]
Thanks for the report Hamish! - seems really strange to be relying on a regex to do this - that code must be quite old! - I've just swapped it out for the core PARAM_EMAIL var which seems to take care of this a bit better - and also supports your .health domain.

Nice work figuring out the changes required to the regex to make it work though! - thanks!

**Comment by hamishdewe** [comment]
Thanks Dan, PARAM_EMAIL is a much better fix.
