### ISSUE TITLE
Chance to incorporate with Simple Certificate

### ISSUE THREAD

**Issue by johnpap21** [catalyst/moodle-mod_facetoface#42]
Hello

I see that you have a patch to integrate with the certificate module, is there a chance or a hint on how to incorporate with Simple Certificates

TIA
John

**Comment by danmarsden** [comment]
Hi John! - we have no plans to work on this at our end, but feel free to submit a pull request for us to review! - if you don't have development skills you could ask for further help in the facetoface forum on moodle.org - thanks!
