### ISSUE TITLE
PHP 7.3 support: Fix cases of continue within switch statements - causes warnings in error.log

### ISSUE THREAD

**Issue by martingreenaway** [catalyst/moodle-mod_facetoface#44]
Since PHP 7.3 a warning is raised (about an existing problem) when `continue;` commands are used within switch statements. Really they act as `break;` statements instead, and one should be using `continue 2;` to achieve continue functionality.  There is a ticket here tracking Moodle core effort to round up and exterminate these instances: https://tracker.moodle.org/browse/MDL-63422 

These warnings are present in the log file when viewing pages and courses that do not contain mod_facetoface activities - e.g. admin and plugin management pages - and clutter up the logs when doing development.

Log messages when tested on Moodle 3.7.1, mod_facetoface 3.4.3 (latest), and PHP 7.3:

> [Mon Mar 23 13:29:02.300560 2020] [php7:warn] [pid 11140] [client [[ip]]:62036] PHP Warning:
> "continue" targeting switch is equivalent to "break".
> Did you mean to use "continue 2"? in /var/www/html/moodle/mod/facetoface/lib.php on line 2426, referer: 
> https://url/admin/index.php?cache=1
> [Mon Mar 23 13:29:02.300701 2020] [php7:warn] [pid 11140] [client 1[[ip]]:62036] PHP Warning:
> "continue" targeting switch is equivalent to "break".
> Did you mean to use "continue 2"? in /var/www/html/moodle/mod/facetoface/lib.php on line 2434, referer:
> https://url/admin/index.php?cache=1
> [Mon Mar 23 13:29:02.301364 2020] [php7:warn] [pid 11140] [client [[ip]]:62036] PHP Warning:
> "continue" targeting switch is equivalent to "break".
> Did you mean to use "continue 2"? in /var/www/html/moodle/mod/facetoface/lib.php on line 3851, referer:
> https://url/admin/index.php?cache=1

**Comment by danmarsden** [comment]
Thanks Martin! - we haven't got anyone using this in 7.3 ourselves yet - feel free to help us work on this by submitting a pull request!

**Comment by markidm** [comment]
Hi Dan, I came across the same warning - Pull request submitted :)

**Comment by danmarsden** [comment]
Thanks @markidm - pull request made sense so I've merged that in.
