### ISSUE TITLE
When did session_form.php get removed? 

### ISSUE THREAD

**Issue by robgalpin** [catalyst/moodle-mod_facetoface#50]
When did session_form.php get removed? Did it get replaced by something else? I am working with an old version that was partially updated to $plugin->version   = 2019011601;    // 3.6.1 update AND added table to enable user interest feature 

We have done a lot of customizations so the update was a little bit of a mashup be tween versions.

I am just wondering where the form validation function is that used to be in session_form.php. ??

**Comment by danmarsden** [comment]
session_form.php was moved to classes/session_form.php in 2015

**Comment by danmarsden** [comment]
would be great to see you submit any pull requests with improvements to the repo here so other people can benefit too!
