### ISSUE TITLE
moodle plugindb update ?

### ISSUE THREAD

**Issue by ak4t0sh** [catalyst/moodle-mod_facetoface#53]
Hi @danmarsden 
Seems you forgot to update plugin DB when you released 3.9 compatible version :) 
Current latest release on plugin DB is 3.4.3 (2018110900) for Moodle 3.5.

TIA

**Comment by danmarsden** [comment]
We hadn't forgotten - I'm reluctant to publish stuff to the plugins db that we haven't tested ourselves all that well, face to face doesn't have any automated tests and we don't have anyone here using it in Moodle 3.9.

If you're saying that it's working for you (and you've tested it) let me know and I'll think about updating the plugins db!

**Comment by ak4t0sh** [comment]
Thanks for your reply (sorry for the delay). 
I had warnings with 3.4.3 on a staging moodle 3.9 so I updated it and only checked it does not crash.
I'll try to give you some feedback when I'll have time to do some more tests

**Comment by danmarsden** [comment]
yeah - that's the limit of what I did too, all good! - just let me know once someone has had a chance to run it through and use it - no urgency on our end! :-)

**Comment by ak4t0sh** [comment]
Hi @danmarsden 
FYI we are using it  on a Moodle 3.9 production instance for 2 months without facing any error :)

**Comment by danmarsden** [comment]
thanks for confirming that! - I've just uploaded this version to the plugins db now for 3.9
