### ISSUE TITLE
increasing (or removing) CALENDAR_MAX_NAME_LENGTH ?

### ISSUE THREAD

**Issue by ak4t0sh** [catalyst/moodle-mod_facetoface#54]
Hi,

Is there a particular reason to limit event name to 15 characters ? It is really short.
https://github.com/catalyst/moodle-mod_facetoface/blob/9a177d52908a710ce47ba79b05b36b402f827bf6/lib.php#L68
https://github.com/catalyst/moodle-mod_facetoface/blob/9a177d52908a710ce47ba79b05b36b402f827bf6/lib.php#L3206

AFAIK technically mdl_event.name is a `longtext` and module name which is used to build the event name is a `varchar(255)`.  
I know that you can use "shortname" if you want to display a specific (and length unlimited) event name but it forces teachers to do double entry if they only want the module name to be displayed completely.  

IMO truncate should be done on display only (and is correctly handle by the calendar) and not during event creation.

**Comment by danmarsden** [comment]
no idea why it was set that short... your guess is as good as mine! - happy to approve a MR that changes that any way you think makes sense! :-)

**Comment by create-martin** [comment]
Is there an update for this issue?
I have clients wondering, why in the calender-fly-over their course-name is cropped.
However, I found out, that setting a short name in the calender options, is a work-around
