### ISSUE TITLE
Customizing the F2F notification messages to allow rich text emails

### ISSUE THREAD

**Issue by chalhoub-university** [catalyst/moodle-mod_facetoface#55]
Hello,

Currently the F2F notifications coming out of the plugin are plain text, however we would like to customize this to include media such as images and colors. An idea is by incorporating the Moodle Atto editor that allows rich text to be created. 

We're planning to begin by modifying the plaintext field in the session confirmation email section to instead used the Moodle Atto editor. Following which we plan to modify any of its other dependencies to accept the rich text and send out better looking emails.

This is an issue we can attempt to work on with a guidance and review from your team. 😄

**Comment by chalhoub-university** [comment]
@danmarsden Pinging for better visibility 😄  Thank you!

**Comment by danmarsden** [comment]
Nice idea! - thanks for the PR with your work so far! unfortunately we don't really have the capacity to work on the patch or provide development mentoring/guidance for free. If you do get it all working please let us know and I should be able to find someone to review and look at including it in the core release though!

Alternatively you might want to ask in the moodle.org community forums for feedback on your patch or for help with the issues you're having so far.

Will be great to see this feature land - all the best!

**Comment by chalhoub-university** [comment]
Thank you @danmarsden for letting us know about this, we are currently working on making it fully functional. We had a quick question regarding the location of code where the form for "Edit Settings" of the block sits. As per our research, the fields in the "Edit Settings" Page of the block come from mod_form.php. But we are trying to locate the function that populates the "Edit Settings" Page of the block with the data in the DB. 

Would this be something you can point us to or perhaps a high level documentation of the plugin?

![image](https://user-images.githubusercontent.com/79912874/118396937-d4e8aa00-b662-11eb-9c9e-0df0865463a3.png)

Thank you

**Comment by danmarsden** [comment]
Best place for those sorts of questions is definitely the moodle community forums.. but ...
see:
https://docs.moodle.org/dev/Activity_modules#mod_form.php
".... This data will be passed to either <modname>_add_instance or <modname>_update_instance depending on whether you are adding a new instance or updating a current one..."

**Comment by chalhoub-university** [comment]
Thank you! We're looking into it 😄

**Comment by chalhoub-university** [comment]
Hi @danmarsden, we have managed to fix the issue earlier, the PR is available at https://github.com/catalyst/moodle-mod_facetoface/pull/56. 

We look forward the review.
