### ISSUE TITLE
Continue vs break when running on PHP 7.4

### ISSUE THREAD

**Issue by logan-reynolds** [catalyst/moodle-mod_facetoface#62]
When running basic operational tests on mod_facetoface version 2020080400 release 3.9.1 on latest Moodle 3.11 with PHP 7.4, the following error is encountered which seems to be related to recent changes in the latest PHP 7.4:

``
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in .../mod/facetoface/lib.php on line 2426
``

**Comment by DrCuriosity** [comment]
This warning appears to have been fixed in #46.

**Comment by danmarsden** [comment]
yeah @logan-reynolds latest code is always in the github repo - looks like we haven't bumped version in version.php for a while but if you download the latest version from github you should be good.
