### ISSUE TITLE
get_all_user_name_fields() has been deprecated in Moodle 3.11

### ISSUE THREAD

**Issue by michael-milette** [catalyst/moodle-mod_facetoface#63]
Adding a new session using FaceToFace on 3.11 throws the following errors:

get_all_user_name_fields() is deprecated. Please use the \core_user\fields API instead
line 3384 of /lib/deprecatedlib.php: call to debugging()
line 3722 of /mod/facetoface/lib.php: call to get_all_user_name_fields()
line 159 of /mod/facetoface/classes/session_form.php: call to facetoface_get_trainers()
line 214 of /lib/formslib.php: call to mod_facetoface_session_form->definition()
line 143 of /mod/facetoface/sessions.php: call to moodleform->__construct()

get_all_user_name_fields() is deprecated. Please use the \core_user\fields API instead
line 3384 of /lib/deprecatedlib.php: call to debugging()
line 167 of /mod/facetoface/classes/session_form.php: call to get_all_user_name_fields()
line 214 of /lib/formslib.php: call to mod_facetoface_session_form->definition()
line 143 of /mod/facetoface/sessions.php: call to moodleform->__construct()

See https://tracker.moodle.org/browse/MDL-45242 for deprecation notice:

The corresponding existing functions are all deprecated: get_extra_user_fields(), get_extra_user_fields_sql(), get_user_field_name(), get_all_user_name_fields(), and user_picture::fields(). All the features from these functions are subsumed into the new API:

https://docs.moodle.org/dev/User_fields

Best regards,

Michael

**Comment by danmarsden** [comment]
Thanks Michael - PR's welcome :-) - we haven't got anyone here using this in 3.11 so it's unlikely we'd get to it ourselves - thanks!

**Comment by michael-milette** [comment]
Thank you!
