### ISSUE TITLE
Feature request: Export list of attendees for a single session

### ISSUE THREAD

**Issue by michael-milette** [catalyst/moodle-mod_facetoface#65]
It is currently possible to export a list of users for all sessions from the view all sessions page. However, when you have a LOT of these sessions, or when a teacher simply wants to have a print out of users along with their contact information, who are enrolled in a particular session. For example, Taking in-person attendance offline and entering the information later), importing attendance records into another application, etc.. It would therefore be really useful to have the ability export users from a single session.

I would therefore like to propose and request that one of the following two options:

- Add an icon for Excel and ODS to download list of attendees for each of the listed sessions in the View All Sessions page; or
- Add to the "Attendees" page to export the list of attendees for that single session. This would be added to the existing  options which include "Take Attendance, Add/Remove Attendees and Go Back.

Best regards,

Michael Milette

**Comment by danmarsden** [comment]
Thanks Michael! - Sadly we have hardly any clients using this plugin in Moodle these days so it's unlikely any feature development will be undertaken on facetoface unless it comes with funding, although we're always happy to review PR's

Moodle workplace contains a face to face style plugin, and so does that other Moodle fork that starts with a "T" so most of our clients with a requirement for this sort of functionality are using one of those,

**Comment by michael-milette** [comment]
No worries @danmarsden , I will submit a PR when it is ready.

**Comment by michael-milette** [comment]
Thank you @danmarsden !
