### ISSUE TITLE
Discount code field optional?

### ISSUE THREAD

**Issue by sk-unikent** [catalyst/moodle-mod_facetoface#7]
Hey,

I've been checking out the new version.
When I set a cost and discount cost I notice you MUST set a discount code field when signing up for the event, shouldn't this be an optional field? Not everyone will have a discount code.

Thanks!
Sky

**Comment by lamiette** [comment]
Hi Sky,

Thanks for reporting this. I've taken this over from a colleague so I'm still getting to grips with what some of the logic is and am working on writing some newer documentation to help with configuration as well. The discount field very well could be erroneously marked as required so I'll have a look as soon as possible and see what I can determine.

Stacey
