### ISSUE TITLE
if(has_condition) check bypasses adding users as participants if they have viewing permissions

### ISSUE THREAD

**Issue by vedantnayar** [catalyst/moodle-mod_facetoface#71]
Hi,

This line in code is currently confusing our team. On adding people to a face-to-face session we also want them to be added as participants on the course. However, this check skips over the latter part when the user has permission to view a course (eg: user is a Manager).

https://github.com/catalyst/moodle-mod_facetoface/blob/1993313aece901391c4265b3d8b4ad8a1f8069b8/editattendees.php#L87

Initially we considered it was a bug, but upon further [checking](https://docs.moodle.org/311/en/Capabilities/moodle/course:view) it seems this is intentional ("Users with this capability are NOT listed as course participants"). 

Can you help advise us whether we can safely remove this line? What happens if a user with elevated permissions (ie, Manager) is added as a participant, and what's the reasoning behind the idea that they are not supposed to be participants? If it helps, upon removing this line people are added as participants irrespective of their roles.

Thanks!
Vedant

**Comment by danmarsden** [comment]
If it works for you - I'd just do it - but it doesn't sound like something we would change in the core code unless we had some form of setting (turned off by default) to allow users that are not normally particpants in a course to be added as participants within face-to-face.

hope that helps!

**Comment by vedantnayar** [comment]
Hi Dan,
That makes sense, thanks! I might go back in at a later date and make it a checkbox, I'll definitely make this a PR if I do so. But for now we'll just remove that line of code. Thanks a bunch!
