### ISSUE TITLE
Fatal error: Cannot redeclare format_duration() and cleanup_session_data on Moodle Workplace

### ISSUE THREAD

**Issue by hdagheda** [catalyst/moodle-mod_facetoface#79]
Getting ```Fatal error: Cannot redeclare format_duration() (previously declared in /var/www/qut-mwp/mod/appointment/lib.php:136) in /var/www/qut-mwp/mod/facetoface/lib.php on line 201```

And `MDL_MANAGERSEMAIL_FIELD` already defined

**Comment by danmarsden** [comment]
Uh... why would you install f2f? Workplace forked and improved it and called it appointment

**Comment by danmarsden** [comment]
Closing as won't fix on the basis of us not supporting workplace, however lots of the code there doesn't comply well with guidelines so no real objections to the pr on the basis of improving code.
