### ISSUE TITLE
Fatal error when navigating to report/eventlist/index.php

### ISSUE THREAD

**Issue by EmilyULCC** [catalyst/moodle-mod_facetoface#8]
Updated plugin to latest version (2.8) on commit hash ca5004b59618371878c7b18fb06ded3c676fb82d
Running 2.8.5

Get a fatal error when going to events list
Coding error detected, it must be fixed by a programmer: Invalid event class name 'mod_facetoface\event\signup', there must be at least one underscore separating object and action words

**Comment by digidoug** [comment]
Seeing exactly the same error on user signup and cancel registration. Running 2.7.0 Build: 2015020900

**Comment by lamiette** [comment]
Hi both,

Thanks for this, it has been reported in a separate thread by others as well so I'll try and prioritise to debug and fix it for you as soon as possible.

Stacey

**Comment by EmilyULCC** [comment]
Hi lamiette,

If possible could you provide me with an update on the timescales for this fix?

**Comment by danmarsden** [comment]
this has been fixed in the latest code available here on github.
