### ISSUE TITLE
Obsolete table CSS and too general cell highlight selector

### ISSUE THREAD

**Issue by skodak** [catalyst/moodle-mod_facetoface#81]
This CSS found in styles.css is no longer necessary, even before it was incorrect because the selectors were too general and could affect other plugins.

```
table.table90 {
    width: 90%;
}
table.table50 {
    width: 50%;
    text-align: left;
}
table.inlinetable {
    display: inline-table;
    border: 0;
}
```
Previously used tables were replaced with divs and spans, which means we can safely remove this obsolete CSS.

Second related problem is use of 'highlight' class in session list. It was introduced at the same time. Solution is to add a class to the session list table and apply the highlight only there.

```
tr.highlight td.cell {
    font-size: 12px;
    line-height: 18px;
}
```

Third problem is too general error class

```
span.errorstring {
    font-size: 12px;
    line-height: 18px;
}
```

**Comment by danmarsden** [comment]
Merged - thanks!

**Comment by skodak** [comment]
hehe, sorry for the noise in my commits and pulls requests, I was learning how github works these days
