### ISSUE TITLE
As an editing teacher, I can select attendance status as completion criteria on a Face to Face instance

### ISSUE THREAD

**Issue by skodak** [catalyst/moodle-mod_facetoface#84]
Hi Dan, I would like to ask if you would be interested in a new feature that adds F2F attendance status to completion criteria? Here is the original description, I am asking before I start cleaning up our current patch for upstreaming:

------

For completion tracking, the Face-to-face module currently only supports the options:

* Do not indicate activity completion
* Students can manually mark the activity as completed
* Show activity as complete when conditions are met

If you select "Show activity as complete when conditions are met" your options are:

* Student must view this activity to complete it
* Student must receive a grade to complete this activity

Face to Face allows the following options "No show", "Partially Attended", or Fully Attended" when taking attendance.  The "Partially Attended" and "Fully Attended" options should be added to the options for "Show activity as complete when conditions are met" to be met.

* Student must be marked "Partially Attended"
* Student must be marked "Fully Attended"

**Comment by danmarsden** [comment]
sounds good! - happy to merge that in when you fire it through! :-)
